# -*- coding: utf-8 -*-
"""Config.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GFOIoBO9VUdOhPx9MgGL0lf46cF5K_Bk
"""

import cv2
import torch 
import torch.nn as nn
# from utils import seed_everything

DATASET='WIDERFACE'
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

NUM_WORKERS = 4
BATCH_SIZE = 32
IMAGE_SIZE = 416
NUM_CLASSES = 1
LEARNING_RATE = 1e-5
WEIGHT_DECAY = 1e-4
NUM_EPOCHS = 100
CONF_THRESHOLD = 0.05
MAP_IOU_THRESH = 0.5
NMS_IOU_THRESH = 0.45
S = [IMAGE_SIZE // 32, IMAGE_SIZE // 16, IMAGE_SIZE // 8]
PIN_MEMORY = True
LOAD_MODEL = True
SAVE_MODEL = True
CHECKPOINT_FILE = "checkpoint.pth.tar"
IMG_DIR = DATASET + "/images/"
LABEL_DIR = DATASET + "/labels/"

ANCHORS = [
    [(0.28, 0.22), (0.38, 0.48), (0.9, 0.78)],
    [(0.07, 0.15), (0.15, 0.11), (0.14, 0.29)],
    [(0.02, 0.03), (0.04, 0.07), (0.08, 0.06)],
]  # Note these have been rescaled to be between [0, 1]


scale = 1.1

# anchors=torch.tensor(ANCHORS[0]+ANCHORS[1]+ANCHORS[2])
# print(anchors)

x=torch.rand((3, 3, 13, 13, 6))

x[...,0].shape

noobj=x[..., 0]>=0.7

x[..., 0:2][noobj].shape

torch.tensor(ANCHORS[0]).reshape(1, 3, 1, 1, 2)

